services:
  account-service:
    build:
      context: ./account-service
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    networks:
      - banking-network
    environment:
      - TRANSACTION_SERVICE_URL=http://transaction-service:8071

  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    ports:
      - "8071:8071"
    networks:
      - banking-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8072:8072"
    networks:
      - banking-network
    environment:
      - ACCOUNT_SERVICE_URL=http://account-service:8070
      - TRANSACTION_SERVICE_URL=http://transaction-service:8071
    depends_on:
      - account-service
      - transaction-service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - banking-network
    environment:
      - VITE_API_URL=http://localhost:8072
    depends_on:
      - user-service

networks:
  banking-network:
    driver: bridge