name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: '23'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: |
        chmod +x account-service/gradlew
        chmod +x transaction-service/gradlew
        chmod +x user-service/gradlew

    - name: Build and Test Account Service
      run: |
        cd account-service
        ./gradlew build test

    - name: Build and Test Transaction Service
      run: |
        cd transaction-service
        ./gradlew build test

    - name: Build and Test User Service
      run: |
        cd user-service
        ./gradlew build test

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build